config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/authenticate', to: 'authentication#authenticate'
      resources :transactions, only: :create
    end
  end

  devise_for :users
  root to: 'users#index'
  resources :users do
    resources :transactions, only: :index
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorize_transaction.rb
class AuthorizeTransaction < Transaction
  belongs_to :related_transaction, foreign_key: :transaction_id, class_name: 'Transaction'

  validates :amount, numericality: { greater_than: 0 }
end

app/models/charge_transaction.rb
class ChargeTransaction < Transaction
  belongs_to :related_transaction, foreign_key: :transaction_id, class_name: 'Transaction'

  validates :amount, numericality: { greater_than: 0 }

  after_create :after_process

  private
    def after_process
      # adjust total_transaction_sum for merchant
      related_transaction.user.save
    end
end

app/models/refund_transaction.rb
class RefundTransaction < Transaction
  belongs_to :related_transaction, foreign_key: :transaction_id, class_name: 'Transaction'

  validates :amount, numericality: { greater_than: 0 }

  after_create :refund_process

  private
    def refund_process
      # set status to refunded for related charged_transaction
      charged_transaction = related_transaction.related_transactions.charge.approved.last
      charged_transaction.update_attribute(:status, 'refunded') if charged_transaction

      # adjust total_transaction_sum for merchant
      related_transaction.user.save
    end
end

app/models/reversal_transaction.rb
class ReversalTransaction < Transaction
  belongs_to :related_transaction, foreign_key: :transaction_id, class_name: 'Transaction'

  validates :amount, absence: true

  after_create :reversal_process

  private
    def reversal_process
      # set status to refunded for related authorized_transaction
      authorized_transaction = related_transaction.related_transactions.authorize.approved.last
      authorized_transaction.update_attribute(:status, 'reversed') if authorized_transaction
    end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  has_many :related_transactions, foreign_key: :transaction_id, class_name: 'Transaction'

  scope :charge, -> { where(type:'ChargeTransaction') }
  scope :authorize, -> { where(type:'AuthorizeTransaction') }
  scope :refund, -> { where(type:'RefundTransaction') }
  scope :reversal, -> { where(type:'ReversalTransaction') }

  enum status: %i(approved reversed refunded error)
  before_validation :asign_uuid, on: :create

  validates :customer_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :uuid, :status, presence: true

  def asign_uuid
    self.uuid ||= SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :transactions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum status: %i(active inactive)

  after_create :assign_default_role
  before_save :cal_total_transaction_sum, if: -> { is_merchant? }

  private
    def cal_total_transaction_sum
      self.total_transaction_sum = transactions.charge.approved.sum(:amount)
    end

    def assign_default_role
      add_role(:merchant) if roles.blank?
    end
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API
    before_action :authenticate_request
    attr_reader :current_api_user

    private
      def authenticate_request
        @current_api_user = AuthorizeApiRequest.call(request.headers)
                                               .result

        render json: {  error: "This is not an authorized request." },
                        status: :unauthorized unless @current_api_user
      end
  end
end

app/controllers/api/v1/authentication_controller.rb
class Api::V1::AuthenticationController < Api::ApplicationController

  skip_before_action :authenticate_request

  def authenticate
    command = AuthenticateUser.call(
                params[:email], params[:password])

    if command.success?
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end
end

app/controllers/api/v1/transactions_controller.rb
class Api::V1::TransactionsController < Api::ApplicationController
  def create
    @transaction = @current_api_user.transactions.new(transaction_params)
        if @transaction.save
          render json: @transaction, status: :created
        else
          render json: { errors: @transaction.errors.full_messages },
                 status: :unprocessable_entity
        end
  end

  private
    def transaction_params
      params.permit(:amount, :status, :customer_email, :customer_phone, :type, :transaction_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

    def configure_permitted_parameters
      added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_user

  def index
    @transactions = @user.transactions.order(created_at: :desc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.with_role(:merchant)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :description, :email, :status, :total_transaction_sum)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | PaymentSystem
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container-fluid
      p.notice = notice
      p.alert = alert

      - if user_signed_in?
        = link_to('Logout', destroy_user_session_path, method: :delete)
      - else
        = link_to('Login', new_user_session_path)
      = yield

app/views/transactions/index.html.slim
h1 Transactions

table.table
  thead
    tr
      th UUID
      th Amount
      th Status
      th Customer Email
      th Customer Phone
      th Transaction Type
      th colspan="3"

  tbody
    - @transactions.each do |transaction|
      tr
        td = transaction.uuid
        td = transaction.amount
        td = transaction.status
        td = transaction.customer_email
        td = transaction.customer_phone
        td = transaction.type

=< link_to 'Back', users_path

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .card
    .card-body
      .row.field
        .col-2.text-right.col-form-label.col-form-label-sm
          = f.label :name
        .col-5
          = f.text_field :name, class: 'form-control form-control-sm'
      .row.field.mb-2
        .col-2.text-right.col-form-label.col-form-label-sm
          = f.label :description
        .col-5
          = f.text_area :description, class: 'form-control form-control-sm'
      .row.field
        .col-2.text-right.col-form-label.col-form-label-sm
          = f.label :email
        .col-5
          = f.text_field :email, class: 'form-control form-control-sm'
    .card-footer
      .actions
        = f.submit 'Submit', class: 'btn btn-sm btn-primary float-left'

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Users

table.table
  thead
    tr
      th Name
      th Description
      th Email
      th Status
      th Total Transaction Sum
      th colspan="4"

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.description
        td = user.email
        td = user.status
        td = user.total_transaction_sum
        td = link_to 'Show', user
        td = link_to 'Show Transactions', user_transactions_path(user)
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Description:
  = @user.description
p
  strong Email:
  = @user.email
p
  strong Status:
  = @user.status
p
  strong Total Transaction Sum:
  = @user.total_transaction_sum

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path